version: '3.3'

services:
  db:
    image: postgres:14.0-alpine
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - db_value:/var/lib/postgresql/data/
    restart: always
    env_file:
      - ./.env
    restart: always
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - db
  backend:
    build: ../backend
    restart: always
    volumes:
      - static_value:/backend/django_static/
      - media_value:/backend/django_media/
    env_file:
      - ./.env
    depends_on:
      - db
  nginx:
    image: nginx:1.19.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/backend/django_static/
      - media_value:/backend/django_media/
    restart:
      always
    depends_on:
      - frontend
      - backend
volumes:
  static_value:
  media_value:
  db_value:
