version: '3.8'
services:
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
  # db:
  #   image: postgres:14.3-alpine
  #   volumes:
  #     - /var/lib/postgresql/data/
  #   env_file:
  #     - ./.env
  # web:
  #   image: marlooooo/foodgram:latest
  #   restart: always
  #   volumes:
  #     - static_value:/app/static/
  #     - media_value:/app/media/
  #   depends_on:
  #     - db
  #   env_file:
  #     - ./.env
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
volumes:
  static_value:
  media_value:

