# Generated by Django 3.2.13 on 2022-06-26 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingridient',
            new_name='Ingredient',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingridients',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(help_text='ингридиенты, необходимые для приготовления блюда', related_name='ingridients', through='recipes.IngridientInRecipe', to='recipes.Ingredient'),
        ),
    ]
