# Generated by Django 3.2.13 on 2022-06-25 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20220624_2237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'default_related_name': 'carts', 'ordering': ('id',), 'verbose_name': 'рецепт в корзине', 'verbose_name_plural': 'рецепт в корзине'},
        ),
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ('user',), 'verbose_name': 'Любимый рецепт', 'verbose_name_plural': 'Любимые рецепты'},
        ),
        migrations.AlterModelOptions(
            name='ingridient',
            options={'ordering': ('id',), 'verbose_name': 'Ингридиент', 'verbose_name_plural': 'Ингридиенты'},
        ),
        migrations.AlterModelOptions(
            name='ingridientinrecipe',
            options={'ordering': ('id',), 'verbose_name': 'Ингридиент в рецепте', 'verbose_name_plural': 'Ингридиенты в рецепте'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('id',), 'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AlterModelOptions(
            name='taginrecipe',
            options={'ordering': ('id',), 'verbose_name': 'тэг рецепта', 'verbose_name_plural': 'тэги рецепта'},
        ),
    ]
